version: "3"

services:
  dev:
    container_name: dev
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    env_file: .env
    restart: unless-stopped

  prod:
    container_name: prod
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    restart: unless-stopped

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
